groups:
  - name: app
    rules:
      - alert: HighP95Latency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[5m])) by (le)) > 0.300
        for: 5m
        labels: { severity: warning }
        annotations: { summary: "p95 latency > 300ms" }

      - alert: High5xxRate
        expr: sum(rate(http_request_duration_ms_count{status=~"5.."}[5m])) / sum(rate(http_request_duration_ms_count[5m])) > 0.05
        for: 5m
        labels: { severity: critical }
        annotations: { summary: "5xx ratio > 5%" }
