services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: "Veysel.12"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"   
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  migrator:
    build: .
    env_file: .env
    command: ["node","dist/migrate.js"]
    depends_on:
      mysql:
        condition: service_healthy
    restart: "no"

  api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    labels:
      - "prometheus.scrape=true"
      - "prometheus.path=/metrics"
      - "prometheus.port=8080"
    restart: unless-stopped

volumes:
  dbdata:
