name: deploy
on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: [main]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export TAG=${{ github.sha }}
            cd /opt/hello-devops
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.REGISTRY_PAT }}
            docker compose pull
            docker compose up -d
