name: gitleaks
on:
  push:
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: zricethezav/gitleaks-action@v2
        with:
          args: "--source . --no-banner --redact"
