name: security
on:
  pull_request:
  push: { branches: ["main"] }
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gitleaks/gitleaks-action@v2
        with: { args: "--redact --no-banner" }

  trivy-fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "table"
          exit-code: "0"

  trivy-image:
    runs-on: ubuntu-latest
    needs: [trivy-fs]
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: local/hello-devops:scan
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: "local/hello-devops:scan"
          ignore-unfixed: true
          format: "table"
          exit-code: "0"
